Addressed compilation error: double energy was not defined. (#75)
* Also include required C header

Signed-off-by: Felix Pultar <felix.pultar@phys.chem.ethz.ch>